# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  rust: circleci/rust@1.5.0
  python: circleci/python@1.4.0

jobs:
  rust-bench:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - rust/format
      - rust/build:
          release: true
      - run:
          name: "[RUST] basic_batched.rs (100_000_000) inserts"
          command: time ./target/release/basic_batched
      - run:
          name: "[RUST] threaded_batched.rs (100_000_000) inserts"
          command: time ./target/release/threaded_batched
  python-bench:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - python/install-packages
      - run:
          name: "[PYTHON] running sqlite3_opt.py (100_000_000) inserts"
          command: time python3 sqlite3_opt.py
      - run:
          name: "[PYTHON] running sqlite3_opt_batched.py (100_000_000) inserts"
          command: time python3 sqlite3_opt_batched.py 

  pypy-bench:
    docker:
      - image: pypy
    steps:
      - checkout
      - run:
          name: "[PYPY] running sqlite3_opt_batched.py (100_000_000) inserts"
          command: time pypy sqlite3_opt_batched.py

workflows:
  rust:
    jobs:
      - rust-bench

  python:
    jobs:
      - python-bench

  pypy:
    jobs:
      - pypy-bench
